version: "3.7"
services:
  opentask:
    build: .
    image: opentask:latest
    container_name: opentask
    env_file: .env
    ports: 
      - "${PORT}:80"
    volumes: 
      - ./logs:/var/log/apache2
    networks: 
      - web
  
  mysql:
    image: mysql:8
    container_name: opentask_db
    environment: 
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=opentask
      - MYSQL_USER=opentask
      - MYSQL_PASSWORD=opentask
    volumes: 
      - ./data/mysql:/var/lib/mysql

    networks: 
      - web

networks:
  web: